#!/bin/sh

download=$(cat /home/themarch/Bureau/result.log | grep "Download:" | cut -d " " -f2 | cut -d "." -f1)
upload=$(cat /home/themarch/Bureau/result.log | grep "Upload:" | cut -d " " -f2 | cut -d "." -f1)

down="400"
up="100"

if [ "$download" -gt "$down" ]
then
	echo "speed download is good"
else
	sendemail -f theodesconta@gmail.com -t theodesconta@gmail.com -s smtp.gmail.com:25 -xu theodesconta@gmail.com -xp Gribouille74% -u MAUVAISE CONNECTION -m "Attention, t'a connextion est mauvaise, contacte le service client." -a /home/themarch/Bureau/result.log
	echo "MAIL SEND"
fi

if [ "$upload" -gt "$up" ]
then
	echo "good upload"
else
	echo "bad upload"
fi
